defaults: &defaults
  host: <%= ENV['DATABASE_HOST'] %>
  user: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  adapter: postgresql
  encoding: unicode

development_defaults: &development_defaults
  <<: *defaults

development:
  <<: *development_defaults
  database: calendar_on_rails_development

test:
  <<: *development_defaults
  database: calendar_on_rails_test

staging:
  <<: *defaults

production:
  <<: *defaults